# basically copied from http://3bb.cc/blog/2020/09/11/github-ci/

name: CI

on:
  # pushes to any branch
  push:
  # prs to master
  pull_request:
    branches: [ master ]
  # manually
  repository_dispatch:

jobs:
  test:
    # i don't care enough to test on multiple platforms or multiple impls
    runs-on: ubuntu-latest
    steps:
      - uses: gefjon/github-action-lisp-ci@v1
        with:
          system-name: 'generator'
          test-system-name: 'generator/test'
